### ISSUE TITLE
Jetson nano  yolov8部署     onnx ->> trt

### ISSUE THREAD

**Issue by icesheeters** [Linaom1214/TensorRT-For-YOLO-Series#122]
Jetpack:4.6
CUDA:10.2.3
cuDNN:8.2.1.32
TensorRt: 8.2.3.0
python:3.8

执行：python export.py -o robot.onnx -e jetson.trt --end2end --v8 -v -w 4
[03/19/2024-16:10:14] [TRT] [V] --------------- Timing Runner: (Unnamed Layer* 302) [PluginV2DynamicExt] (PluginV2)
[03/19/2024-16:10:14] [TRT] [V] Deleting timing cache: 1439 entries, 2433 hits
[03/19/2024-16:10:14] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 908, GPU 2849 (MiB)
[03/19/2024-16:10:14] [TRT] [E] 2: [pluginV2DynamicExtRunner.cpp::execute::115] Error Code 2: Internal Error (Assertion status == kSTATUS_SUCCESS failed.)
[03/19/2024-16:10:14] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::417] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)
Traceback (most recent call last):
  File "export.py", line 316, in <module>
    main(args)
  File "export.py", line 276, in main
    builder.create_engine(args.engine, args.precision, args.calib_input, args.calib_cache, args.calib_num_images,
  File "export.py", line 269, in create_engine
    with self.builder.build_serialized_network(self.network, self.config) as engine, open(engine_path, "wb") as f:
AttributeError: __enter__

大佬，这个是因为cuda或者TensorRt的版本太低了导致的吗？

**Comment by icesheeters** [comment]
解决了，不用端到端优化就好了

**Comment by Linaom1214** [comment]
@icesheeters  EFNMS plugin 在8.4才引入
