### ISSUE TITLE
ValueError: setting an array element with a sequence. YOLOv10推理問題

### ISSUE THREAD

**Issue by yeh111w** [Linaom1214/TensorRT-For-YOLO-Series#132]
```
(yolov10) PS D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python> python trt.py -e yolov10n.trt  -i src/test.png -o yolov10-1.jpg
Namespace(engine='yolov10n.trt', image='src/test.png', output='yolov10-1.jpg', video=None, end2end=False)
643.9112716024184 FPS
Traceback (most recent call last):
  File "D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python\trt.py", line 31, in <module>
    origin_img = pred.inference(img_path, conf=0.1, end2end=args.end2end)
  File "D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python\utils\utils.py", line 143, in inference
    predictions = np.reshape(data, (1, -1, int(5+self.n_classes)))[0]
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\numpy\core\fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\numpy\core\fromnumeric.py", line 45, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
```
用export.py導出後執行推理的報錯 不知是哪裡出現錯誤
感謝相助

**Comment by Linaom1214** [comment]
> ```
> (yolov10) PS D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python> python trt.py -e yolov10n.trt  -i src/test.png -o yolov10-1.jpg
> Namespace(engine='yolov10n.trt', image='src/test.png', output='yolov10-1.jpg', video=None, end2end=False)
> 643.9112716024184 FPS
> Traceback (most recent call last):
>   File "D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python\trt.py", line 31, in <module>
>     origin_img = pred.inference(img_path, conf=0.1, end2end=args.end2end)
>   File "D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python\utils\utils.py", line 143, in inference
>     predictions = np.reshape(data, (1, -1, int(5+self.n_classes)))[0]
>   File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\numpy\core\fromnumeric.py", line 285, in reshape
>     return _wrapfunc(a, 'reshape', newshape, order=order)
>   File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
>     return _wrapit(obj, method, *args, **kwds)
>   File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\numpy\core\fromnumeric.py", line 45, in _wrapit
>     result = getattr(asarray(obj), method)(*args, **kwds)
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
> ```
> 
> 用export.py導出後執行推理的報錯 不知是哪裡出現錯誤 感謝相助
ython trt.py -e yolov10n.trt  -i src/test.png -o yolov10-1.jpg --end2end

**Comment by yeh111w** [comment]
我在utils.py新增了一條print(data)發現偵測的結果好像有問題
```
[array([[[ 1.9601971e+02,  2.2289633e+02,  2.9550989e+02,  5.3106329e+02],
        [ 1.9601971e+02,  2.2289633e+02,  2.9550989e+02,  5.3106329e+02],
        [ 5.1306451e+02,  4.7019894e+02,  6.3866949e+02,  6.3975427e+02],
        ...,
        [ 2.5207825e+02, -2.4902344e-01,  3.1788458e+02,  7.6139603e+01],
        [ 1.9586200e+02,  2.8996176e+02,  2.1591295e+02,  3.5945953e+02],
        [ 6.3340332e+02,  3.9098724e+02,  6.4008246e+02,  4.8893842e+02]]],
      dtype=float32), array([300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300.], dtype=float32), array([[9.4639885e-01, 2.5714198e-04, 1.8961741e-04, 1.5356240e-04,
        1.3765463e-04, 1.1412239e-04, 7.7827535e-05, 7.7221921e-05,
        6.9221838e-05, 5.2662068e-05, 5.2252268e-05, 5.0250615e-05,
        4.5044595e-05, 4.5044595e-05, 4.4346274e-05, 3.5913010e-05,
        3.3214194e-05, 3.1201915e-05, 3.0241959e-05, 2.9541423e-05,
        2.7108799e-05, 2.6274773e-05, 2.2827997e-05, 2.2299198e-05,
        2.1782649e-05, 1.9679024e-05, 1.9373936e-05, 1.7917988e-05,
        1.7231572e-05, 1.7231572e-05, 1.7097478e-05, 1.5206840e-05,
        1.5088502e-05, 1.4971084e-05, 1.4971084e-05, 1.2508841e-05,
        1.2314911e-05, 1.1843138e-05, 1.1659530e-05, 1.1300809e-05,
        9.2958098e-06, 9.0804742e-06, 8.6646533e-06, 8.5303209e-06,
        8.0134996e-06, 7.2963790e-06, 6.7480519e-06, 6.1441742e-06,
        5.9551394e-06, 5.7719199e-06, 5.5076057e-06, 5.3381555e-06,
        5.2966138e-06, 5.2553960e-06, 5.0937051e-06, 4.9369892e-06,
        4.9369892e-06, 4.5659704e-06, 4.5659704e-06, 4.4254903e-06,
        4.2228335e-06, 4.1250123e-06, 4.0929112e-06, 4.0294567e-06,
        4.0294567e-06, 3.8449352e-06, 3.8150138e-06, 3.4465788e-06,
        3.3405393e-06, 3.2631560e-06, 3.2125654e-06, 2.9944408e-06,
        2.7911265e-06, 2.6425857e-06, 2.6425857e-06, 2.5612824e-06,
        2.5215734e-06, 2.5019501e-06, 2.4824801e-06, 2.4824801e-06,
        2.4439928e-06, 2.4061023e-06, 2.3687992e-06, 2.3687992e-06,
        2.1907815e-06, 2.1907815e-06, 2.1737328e-06, 2.1568167e-06,
        2.0261421e-06, 1.9792067e-06, 1.9792067e-06, 1.9485219e-06,
        1.9485219e-06, 1.9333584e-06, 1.8592929e-06, 1.8448236e-06,
        1.7603431e-06, 1.7603431e-06, 1.7061833e-06, 1.6536895e-06,
        1.6408205e-06, 1.6028110e-06, 1.5903378e-06, 1.5779617e-06,
        1.5779617e-06, 1.5175111e-06, 1.5057017e-06, 1.5057017e-06,
        1.5057017e-06, 1.4939843e-06, 1.4708222e-06, 1.4593761e-06,
        1.4593761e-06, 1.4367506e-06, 1.4367506e-06, 1.4255698e-06,
        1.3709573e-06, 1.3081766e-06, 1.2979964e-06, 1.2878952e-06,
        1.2778728e-06, 1.2679283e-06, 1.2580613e-06, 1.2482709e-06,
        1.2289182e-06, 1.1544621e-06, 1.1277189e-06, 1.1277189e-06,
        1.1015954e-06, 1.0845167e-06, 1.0845167e-06, 1.0845167e-06,
        1.0511496e-06, 1.0188093e-06, 1.0030142e-06, 9.7215468e-07,
        9.4224464e-07, 9.2763645e-07, 9.1325484e-07, 8.9209925e-07,
        8.7826857e-07, 8.7143388e-07, 8.7143388e-07, 8.4462266e-07,
        8.4462266e-07, 8.2505704e-07, 8.1863635e-07, 8.1863635e-07,
        8.1863635e-07, 8.0594458e-07, 7.9967270e-07, 7.9344960e-07,
        7.9344960e-07, 7.9344960e-07, 7.8114829e-07, 7.8114829e-07,
        7.8114829e-07, 7.6903780e-07, 7.5711495e-07, 7.5711495e-07,
        7.4537701e-07, 7.4537701e-07, 7.2244416e-07, 7.2244416e-07,
        7.1124367e-07, 7.0021690e-07, 7.0021690e-07, 6.9476783e-07,
        6.8936106e-07, 6.5267392e-07, 6.4255522e-07, 6.3755476e-07,
        6.3259330e-07, 6.2767037e-07, 6.2767037e-07, 6.2767037e-07,
        6.2278588e-07, 6.1793929e-07, 6.1793929e-07, 6.1793929e-07,
        6.0835902e-07, 6.0835902e-07, 6.0835902e-07, 6.0362476e-07,
        5.9892727e-07, 5.8505316e-07, 5.8050028e-07, 5.8050028e-07,
        5.7150044e-07, 5.7150044e-07, 5.4960663e-07, 5.4532956e-07,
        5.2035710e-07, 5.2035710e-07, 4.9652823e-07, 4.9652823e-07,
        4.8883027e-07, 4.8883027e-07, 4.8883027e-07, 4.8125162e-07,
        4.7379055e-07, 4.7379055e-07, 4.5921357e-07, 4.5209413e-07,
        4.5209413e-07, 4.5209413e-07, 4.5209413e-07, 4.5209413e-07,
        4.3818463e-07, 4.2470310e-07, 4.2470310e-07, 4.1811876e-07,
        4.1163639e-07, 4.0525458e-07, 3.9897168e-07, 3.9897168e-07,
        3.9278621e-07, 3.9278621e-07, 3.9278621e-07, 3.9278621e-07,
        3.9278621e-07, 3.9278621e-07, 3.8070144e-07, 3.8070144e-07,
        3.7479921e-07, 3.7479921e-07, 3.7479921e-07, 3.7479921e-07,
        3.6898848e-07, 3.6898848e-07, 3.6898848e-07, 3.6898848e-07,
        3.6326784e-07, 3.6326784e-07, 3.5763591e-07, 3.5763591e-07,
        3.5485274e-07, 3.5209129e-07, 3.5209129e-07, 3.4663262e-07,
        3.4125858e-07, 3.3075915e-07, 3.2563122e-07, 3.2563122e-07,
        3.2058279e-07, 3.2058279e-07, 3.2058279e-07, 3.1561260e-07,
        3.1561260e-07, 3.1315648e-07, 3.1071949e-07, 3.1071949e-07,
        3.0590220e-07, 3.0590220e-07, 3.0115964e-07, 2.9649058e-07,
        2.9649058e-07, 2.9189394e-07, 2.8736855e-07, 2.8736855e-07,
        2.8736855e-07, 2.8291333e-07, 2.8291333e-07, 2.8291333e-07,
        2.7852715e-07, 2.7852715e-07, 2.7852715e-07, 2.7852715e-07,
        2.7420899e-07, 2.6995778e-07, 2.6577246e-07, 2.6577246e-07,
        2.6577246e-07, 2.6577246e-07, 2.6165205e-07, 2.5961586e-07,
        2.5759553e-07, 2.5759553e-07, 2.5360185e-07, 2.4967014e-07,
        2.4198860e-07, 2.4198860e-07, 2.4198860e-07, 2.4198860e-07,
        2.4198860e-07, 2.3823691e-07, 2.3454339e-07, 2.3090713e-07,
        2.3090713e-07, 2.3090713e-07, 2.3090713e-07, 2.3090713e-07,
        2.3090713e-07, 2.2732723e-07, 2.2732723e-07, 2.2732723e-07,
        2.2033313e-07, 2.2033313e-07, 2.1861847e-07, 2.1691720e-07]],
      dtype=float32), array([[0., 1., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 2., 0., 0., 2., 0., 0., 2., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 2., 2., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)]
```

**Comment by yeh111w** [comment]
> > ```
> > (yolov10) PS D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python> python trt.py -e yolov10n.trt  -i src/test.png -o yolov10-1.jpg
> > Namespace(engine='yolov10n.trt', image='src/test.png', output='yolov10-1.jpg', video=None, end2end=False)
> > 643.9112716024184 FPS
> > Traceback (most recent call last):
> >   File "D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python\trt.py", line 31, in <module>
> >     origin_img = pred.inference(img_path, conf=0.1, end2end=args.end2end)
> >   File "D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python\utils\utils.py", line 143, in inference
> >     predictions = np.reshape(data, (1, -1, int(5+self.n_classes)))[0]
> >   File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\numpy\core\fromnumeric.py", line 285, in reshape
> >     return _wrapfunc(a, 'reshape', newshape, order=order)
> >   File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
> >     return _wrapit(obj, method, *args, **kwds)
> >   File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\numpy\core\fromnumeric.py", line 45, in _wrapit
> >     result = getattr(asarray(obj), method)(*args, **kwds)
> > ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 用export.py導出後執行推理的報錯 不知是哪裡出現錯誤 感謝相助
> > ython trt.py -e yolov10n.trt  -i src/test.png -o yolov10-1.jpg --end2end
D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python> python trt.py -e yolov10n.trt -i src/test.png -o yolov10-1.jpg --end2end
Traceback (most recent call last):
  File "D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python\trt.py", line 31, in <module>
    origin_img = pred.inference(img_path, conf=0.1, end2end=args.end2end)
  File "D:\python test\yolov10\TensorRT-For-YOLO-Series-cuda-python\utils\utils.py", line 138, in inference
    final_boxes -= dwdh
ValueError: operands could not be broadcast together with shapes (300,) (4,) (300,)
這是模型出問題嗎?
