### ISSUE TITLE
Problem exporting with end2end

### ISSUE THREAD

**Issue by vebjornbl** [Linaom1214/TensorRT-For-YOLO-Series#80]
Hey, I have an issue exporting a model when I run `py export.py -o model.onnx -e model.trt --end2end --v8`

```
[01/25/2023-15:10:56] [TRT] [F] Validation failed: score_activation}tion missing required fields: {
C:\_src\plugin\common\plugin.cpp:41

[01/25/2023-15:10:56] [TRT] [E] Unknown exception
Traceback (most recent call last):
  File "export.py", line 307, in <module>
    main(args)
  File "export.py", line 266, in main
    builder.create_network(args.onnx, args.end2end, args.conf_thres, args.iou_thres, args.max_det, v8=args.v8)
  File "export.py", line 208, in create_network
    layer = self.network.add_plugin_v2([boxes.get_output(0), scores.get_output(0)], nms_layer)
TypeError: add_plugin_v2(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.INetworkDefinition, inputs: List[tensorrt.tensorrt.ITensor], plugin: tensorrt.tensorrt.IPluginV2) -> tensorrt.tensorrt.IPluginV2Layer

Invoked with: <tensorrt.tensorrt.INetworkDefinition object at 0x000001AEF00543F0>, [<tensorrt.tensorrt.ITensor object at 0x000001AEF02DA8F0>, <tensorrt.tensorrt.ITensor object at 0x000001AEF0606BF0>], None
```

It works without end2end enabled, so I believe I have installed things correctly, any idea what I can do?

* Windows 10
* Python 3.8.10
* Cuda 10.2, cuDNN 8.6.0
* TensorRT 8.4.1.5
* pycuda 2022.2.2

**Comment by zeyad-mansour** [comment]
Hey, this error arises because the IPluginV2 object isn't created properly. I opened a pull request fixing this issue.

**Comment by vebjornbl** [comment]
> Hey, this error arises because the IPluginV2 object isn't created properly. I opened a pull request fixing this issue.

Thanks, that fixed it :)
